### PR TITLE
Added Revit Documentation

### PR DESCRIPTION
**Pull request by alelom**
This PR:

- adds the Revit documentation from the old wiki
- removes all references to Dynamo across the entire documentation (including the newly ported Revit wiki docs)
- does some minor restructuring and rewriting to the newly ported Revit wiki docs in order to allow MkDocs to correctly expose the its content in the search function, and for readability.

There are many links in the newly ported Revit wiki docs that point between pages of the documentation. Many of those are broken. It takes time to fix them, so I propose to raise a separate issue and PR to finish that work. @pawelbaran 

### To preview locally (useful to review)

https://bhom.xyz/documentation/Contributing/Editing-the-documentation/#previewing-the-website-before-pushing-to-the-repository

### CODE REVIEW

**Comment by pawelbaran** [comment]
Thanks @alelom for raising this PR 💪 I ignored the broken links for now (as suggested in the PR description), and focused on the content, which looks really good. However, I found a few potential issues:
- Revit adapter details page has not been migrated at all from what I can see
- [Revit <-> BHoM conversion](https://github.com/BHoM/Revit_Toolkit/wiki/Revit-BHoM-conversion) seems to also be missing
- _Revit Adapter / Introduction:_ I would move family library to _Push_ section, leaving only a link under _Settings_ - the concept is very specific to pushing and may cause more noise than value in the main page
- _Revit Adapter / Setup in Revit Plugin:_ I would remove the _Plugin_ suffix - noise from users' perspective, besides that I would put it in front of setup in GH and Excel (Revit _always_ needs to be enabled)
- _Revit details and coding / Matching (...):_ `RevitIdentifiers` is not formatted
- _Pull / Advanced pull from Revit:_ I would put mapping of Revit families in a separate subpage - now it is a bit of a mixture of everything and nothing
- Revit Push flow-chart explanation (for coders) - duplicate under main push page and advanced subpage - I would rather move it to details and coding

In general, I would consider sticking to the page structure as in the Revit_Toolkit wiki, I have put quite a bit of effort into it and I think it is still quite OK. One major change that makes quite a lot of change to me is migration of details pages to a separate node for coders - can be a good way to decouple user documentation from dev docs. What do you think?

**Comment by alelom** [comment]
> Revit adapter details page has not been migrated at all from what I can see

Integrated in other pages for readability

> [Revit <-> BHoM conversion](https://github.com/BHoM/Revit_Toolkit/wiki/Revit-BHoM-conversion) and https://github.com/BHoM/Revit_Toolkit/wiki/Conventions seem to also be missing

It's present actually, only in another folder

> Revit Adapter / Introduction: I would move family library to Push section, leaving only a link under Settings - the concept is very specific to pushing and may cause more noise than value in the main page
Revit Adapter / Setup in Revit Plugin: I would remove the Plugin suffix - noise from users' perspective, besides that I would put it in front of setup in GH and Excel (Revit always needs to be enabled)
Revit details and coding / Matching (...): RevitIdentifiers is not formatted
Pull / Advanced pull from Revit: I would put mapping of Revit families in a separate subpage - now it is a bit of a mixture of everything and nothing
Revit Push flow-chart explanation (for coders) - duplicate under main push page and advanced subpage - I would rather move it to details and coding

Happy for you or someone else to do all these changes -- I would like to get more people involved which will be better than me at writing these docs. However, having something not perfect is better than not having anything at all – especially because we need to centralise our knowledge of the BHoM rather than having it split into different Wikis or pages. 

I suggest merging and I'll raise an issues with these comments.

**Comment by al-fisher** [comment]
This is great - thanks for pushing @alelom.

>> One major change that makes quite a lot of change to me is migration of details pages to a separate node for coders - can be a good way to decouple user documentation from dev docs.

> This is actually something that @al-fisher and me have monitored extensively as a critical point for newcomers. Totally agree, we can do even better in separating dev docs from user docs.

Yes!! 😄 Totally! I have been starting to consider a further clearer separation of  "_How to guides_" for Coders and Visual Programmers - as they are very different audiences.

I have sketched out the below - with a new clearer section called **Guides and Tutorials** - separating Visual Programming and Coding. Will raise an issue for discussion so we can coordinate actioning around this.

But great timely push on this @alelom @pawelbaran. 
I agree - will be great to merge with raised issues to incrementally perfect going forward if we can

<details>

**_WIP proposed Documentation menu_**

- Welcome
- Introduction
    - What is the BHoM for?
    - Installing the BHoM 
    - Using the BHoM
    - The BHoM Toolkit
    - The BHoM Code Organisation
    - Technical philosophy

- BHoM oM
    - **What is the oM? Commmon Language
    - The Object Model (oM): define new objects
    - Geometry_oM
    - Conventions
    - ...
- BHoM Engine
    - What is the Engine
    - ...
- BHoM Adapter
    - ...
- BHoM UI
    - ...

- Contributing
    - Raising issue
    - Editing docs etc.
    - ...
    - ** Development Procedure

- Guides and Tutorials
    - **Computational Thinking with BHoM
        - **Getting started for designers
    - **Visual Programming with BHoM**
        - Getting started for scripters
        - **Custom Objects
        - **Accessing Datasets
        - **Revit_Toolkit
            - **Revit Adpater in GH etc.
            - **Push/Pull etc. etc.
        - **Structural Analysis Models
    - **Coding with BHoM**
        - Getting started for developers
        - **Calling Datasets from code
        - **Revit_Toolkit
            - **Code Structure/Parameters etc.

</details>

**Comment by pawelbaran** [comment]
Thanks @alelom @al-fisher - all makes sense. One thing concerns me, however: this PR is aiming to port and degrade (break links etc.) a (hopefully) well working Wiki based on the argument that it is better to have something not perfect is better than not having anything at all. Are we 100% sure it is better to have information doubled, with one source being clearly rushed in? I am not saying we should fix everything in this PR @alelom, do not get me wrong, I am just afraid we will create an impression that BHoM is 'unfinished', which I believe is something we are trying to tackle. It would also be great to understand what logic follows restructuring of the Wiki and what is the ultimate objective of the actions taken. Where does the user/dev documentation go, what is the split and how do we cross reference the two? Likely it has all been discussed and I am simply out of the loop, but it would be really helpful to spread this knowledge equally across the entire team before we ask it to do any work. Finally, it is always good to raise issues, but is there any plan behind who will action them and when? We do not have it in our roadmap atm and I do not think anything before the new year is feasible, being realistic, so they may hang for a bit at least.

Happy to jump on a quick call to streamline the discussion, cheers!

**Comment by alelom** [comment]
>  Are we 100% sure it is better to have information doubled, with one source being clearly rushed in?

The information in the Revit_Tookit wiki is also unfinished -- with pending removal actions on the Dynamo_Toolkit mentions, old examples that don't open anymore, and references to the BHoM Wiki that no longer exist. An user using it will be utterly confused, and while this PR is absolutely not perfect, I personally believe it is a step in the right direction, with lots of space for improvement. By placing our material centrally in the Docs, people can comment and raise issues, rather than leaving it in a spot where it's harder to reach, has no clear mechanism to highlight shortcomings and errors. For this reason, I don't think I'd describe this PR material as _rushed in_, but rather as _at least done to an extent_ – things can always be improved.

The issue I see with always waiting for the _perfect_ amount of stuff being done, rather than _done to an extent_, is that it never gets done. Merging this PR would allow people to crowd around and improve docs into a central space. I have happily dedicated some of my time to this effort in order to attract more people – including Revit people – to add to the docs. 

With limited time at my disposal, I'd be happy to either:
1. merge this PR as is, raising relevant issues, then let Revit people like @pawelbaran improve it as better suited.
2. close this PR and lose this work, and let Revit people do another PR to add to the Docs. It just seems unlikely that any priority will be given to a similar effort anytime soon. At the same time, the more we wait to add to the docs, the less we tap into the potential of more highlighting shortcoming and helping shaping the docs. We have already had discussions with potential users searching for more info in the docs and not finding it, and I believe it would be important for us to prioritize actions here. This PR was an effort in this sense.

**Comment by pawelbaran** [comment]
@alelom I appreciate your good will and effort taken regardless of limited time and headspace - this is great! However, I still genuinely do not understand where are we heading with this in terms of scope and planning, who will own or action any further work, I do not feel my questions were answered.

Of course we can get this PR merged and create one more open thread to add to our cognitive overload, but I really think we can be better off with a short discussion about what are we trying to achieve with here @alelom @al-fisher.

**Comment by al-fisher** [comment]
This sounds good! 
Yes makes sense to grab a session together to discuss so all on same page. @pawelbaran @alelom 
@pawelbaran do you want to find a slot when you are back from travelling? 😄 

I am also happy and keen to support and put a bit of time on this to progress it - as really keen to ramp up the co-authorship and wider use of bhom documentation

**Comment by pawelbaran** [comment]
Sure, I will send an invite in a sec. To be clear: I am all in to support the efforts we are taking here, just want to understand the wider framework we are building around the topic to drive it from the Revit end 💪 Cheers!

**Comment by al-fisher** [comment]
Thanks @pawelbaran @travispotterBH - for a great session on this. 

As discussed we will action the following:

1.  @al-fisher to first push the new agreed primary menu structure suggested above in comment https://github.com/BHoM/documentation/pull/83#issuecomment-1819050516 . Particularly focusing on the new "_Guides and Tutorials"_ section and separating out 

- _Visual Programming with BHoM_
- _Coding with BHoM_

2. @pawelbaran to then pick up this Revit Toolkit PR and do a pass getting ready for merge - including mapping into this new structure of Visual Programming vs Coding - which will help address the comment about targeting our two main user groups separately. 

Thanks all

**Comment by al-fisher** [comment]
FYI @pawelbaran I have pushed the creation of the new Guides and Tutorials section to main.

I will be continuing to sort the rest of the menu - _i.e. the Contributing/Conventions/Development sections etc._ aligning with the new structure.
So we can keep in close communication to keep coordinated. But you have your new home for your Revit Toolkit pages 😄 

Also note the tips on managing the links raised as an issue here which we will add to the contributing to docs page asap

**Comment by pawelbaran** [comment]
@al-fisher I have cleaned up, fixed and slightly refactored the Revit docs - please have a look!

**Comment by al-fisher** [comment]
Awesome! Thanks @pawelbaran 
I will take a look!

**Review by al-fisher — APPROVED** [review]
Thanks @pawelbaran and @alelom for this push! I think this is great to merge!

@pawelbaran I think your re-mapping of the material across the Visual Programming vs Coding works really well too! Love it!

**Comment by alelom** [comment]
Hey @pawelbaran ! This is awesome, it looks great! Thank you for doing it! 🚀 

It all looks perfectly clear and much better, also I see that maybe all links are already working!
There's a workflow that we discovered with @al-fisher to do a proper link check and verify that all link work, this one: https://github.com/BHoM/documentation/issues/84. In a nutshell, we can basically leverage some Visual Studio Code extension to check links.

I tried using the link checker on this PR and there are many "false flags" appearing. See this page for example:
image

These are links that actually work, because they get translated to a valid URL by MkDocs, but that cannot be determined as valid by the visual studio Link checker, which requires a specific format to be used (as highlighted in #84). 

So with @al-fisher we were thinking of uniform all links and Markdown filenames to that format in order to get the powerful link checking ability correctly working. I can fix this myself in a separate issue, it simply requires:
1. making sure that all `.md` files do not contain whitespaces (use dashes or underscores instead)
2. shift-drag `.md` files where a link is required, the correct link will be created.

Happy to do it myself -- mostly commenting this here for visibility as this action will change the files edited by @pawelbaran (just the URLs, I won't touch the content! 😄 )

**Comment by pawelbaran** [comment]
Sounds good @alelom! Glad you did not intend to do it in this PR - I was trigger happy with getting it merged 😃 Feel free to restructure the file structure and link format as you like 👍

**Comment by alelom** [comment]
I just raised a separate issue: #86 -- it will target all files in the Documentation, so not only those in this PR, better to do it separately for sure :)

**Comment by al-fisher** [comment]
This sounds good @alelom 

As per https://github.com/BHoM/documentation/issues/85 - much of the strategic restructure has been completed and is on main and deployed now. 

Left to do though is further consolidation of Contributing, Development and DevOps and moving a few more files about.
Which I was going to continue to do.
Shall we coordinate next steps?

**Comment by al-fisher** [comment]
See comment here: https://github.com/BHoM/documentation/issues/85#issuecomment-1825732267

**Comment by FraserGreenroyd** [comment]
@al-fisher can we coordinate on changes to DevOps, as a number of those links are referenced in the bot to provide feedback in some of the automated checks, so would be good to ensure we update that at the same time 😄

**Comment by al-fisher** [comment]
Thanks @FraserGreenroyd - will likely leave https://bhom.xyz/documentation/DevOps/ as the root for now. But coordination sounds really good - will tag in PR when raised 😄

**Comment by alelom** [comment]
Just because I now noticed it, can I suggest as a future action the addition of an `index.md` file to the DevOps root so that https://bhom.xyz/documentation/DevOps/ doesn't point to a 404? 

It can simply be a welcome page saying "this is the section dedicated to DevOps". It's a general rule I've been following for every section in the documentation, it's useful to point to them. Happy to raise an issue

**Comment by al-fisher** [comment]
Good spot @alelom!  I have raised issue here: https://github.com/BHoM/documentation/issues/91

**Pull request merged**
