### PR TITLE
Fix Typo in Template 

### LINKED ISSUE #50: Introduced typo `the from namespace` - sorry I didn't review in time.
Introduced typo `the from namespace` - sorry I didn't review in time.

_Originally posted by @alelom in https://github.com/BHoM/documentation/pull/46#discussion_r786176783_

### PR DESCRIPTION
**Pull request by travispotterBH**
Closes #50 

Simple typo fix.

### Changelog

- `Query` - Partial class template modified for typo in comment on namespace naming.
- `Compute` - Partial class template modified for typo in comment on namespace naming.
- `Convert` - Partial class template modified for typo in comment on namespace naming.
- `Modify` - Partial class template modified for typo in comment on namespace naming.
- `Create` - Partial class template modified for typo in comment on namespace naming.

### CODE REVIEW

**Review by alelom — CHANGES_REQUESTED** [review]
Thanks for this @travispotterBH ! However as the issue states the bug is introduced in every method template, so this PR should target all of them. See e.g. https://github.com/BHoM/documentation/blob/main/templates/Engine%20method%20templates/ConvertTemplate/ConvertTemplate.cs

**Comment by travispotterBH** [comment]
> Thanks for this @travispotterBH ! However as the #50 states the typo is introduced in every method template, so this PR should target all of them. See e.g. https://github.com/BHoM/documentation/blob/main/templates/Engine%20method%20templates/ConvertTemplate/ConvertTemplate.cs

😬 you're right! took care of Compute, Query, Create, Convert, Modify.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by travispotterBH** [comment]
@alelom can you review so we can have this in the beta. Thanks!

**Review by alelom — APPROVED** [review]
Thank you for this fix!

**Pull request merged**
